Sprint 3/step 1
ilya-120/react-burger pull request #5
Opened 2022-11-02 12:41 UTC by ilya-120

2022-11-02 15:56 UTC, randomroot requested changes
**Доброго времени суток!**
 
У вас получилась **отличная** работа, **прекрасные** лоадеры и информационные сообщения, **правильно** построен роутинг в приложении, **настроены** процессы по работе с пользователем, так держать 👍 

Однако, для успешной сдачи, вам необходимо **исправить** замечания, отмеченные в рамках ревью в соответствующих комментариях. Также, присутствуют идеи по **улучшению** вашего кода, предлагаемые вам на рассмотрение.

**Обратите особое внимание на то, что в текущей реализации:**
1) если пользователь авторизовался на сайте, а затем перезагрузил страницу - его статус не восстанавливается, хотя нужные токены лежать в кукисах и `localStorage`, что приводит к необходимости повторно выполнять логин;
2) Время жизни токена в кукисах = `Session`, что означает его удаление автоматическое после закрытия браузера. Имеет смысл добавить такому `cookie` значение параметра `expires` на 20 минут (время жизни токена вы можете проверить, скопировав его на сайт https://jwt.io, искомое значение - справа разница между значениями `iat` и `exp`), чтобы при следующем посещении сайта можно было им снова воспользоваться :)

**Успешного вам рефакторинга и хорошего настроения!** 🐈

2022-11-02 15:56 UTC, randomroot commented on src/utils/utils.js
> +export function setCookie(name, value, props) {
🟡 **Можно улучшить:**

В тренажере приводится не совсем корректный пример этой функции, там не задается **path** и возможна ситуация, когда на разных страницах в cookies будут разные токены, поэтому в `props.path` нужно задавать корень сайта `path: '/'`

2022-11-02 15:56 UTC, randomroot commented on src/components/App/App.js
> +                    style={{ textAlign: "center" }}
🔴 **Нужно исправить:**

Инлайновые стили следует использовать только в крайних случаях, когда другими методами не получается задать стилизацию объекта, следует перенести такие стили в CSS файлы в отдельные классы и задавать именно имя класса в пропс.

2022-11-02 15:56 UTC, randomroot commented on src/components/App/App.js
> +            <Route path="/login"
🔴 **Нужно исправить:**

Имеет смысл перенести `<Route` непосредственно внутрь `ProtectedRouteOnLogin` и `ProtectedRoute`, чтобы они возращали именно компонент пути (и название тогда будет совпадать с действительностью). Плюс, будет удобно сразу наблюдать, когда есть просто `Route` - для анонимов, и два других вариантов для авторизованных пользователей :)

2022-11-02 15:56 UTC, randomroot commented on src/components/AppHeader/AppHeader.js
> +                  type={`${ pathname.slice(0, 7) === "/orders" ? "" : "secondary"}`}
🟡 **Можно улучшить:**

Метод `slice`, создающий новую строку, можно заменить на метод `startsWith` (см. https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith)

2022-11-02 15:56 UTC, randomroot commented on src/utils/StellarBurgersApi.js
> +      ...headers,
🟡 **Можно улучшить:**

Копию в этом случае создавать необязательно т.к. вы не изменяете объект :)

2022-11-02 15:56 UTC, randomroot commented on src/utils/StellarBurgersApi.js
> +  const res_1 = await checkResponse(res);
🔴 **Нужно исправить:**

Названия переменных следует приводить к формату `camelCase`

2022-11-02 15:56 UTC, randomroot commented on src/services/actions/amplifierActions/user.js
> +      res && res.success
🟡 **Можно улучшить:** 

Использование тернарного оператора целесообразно, когда возвращается значение. В текущей ситуации - происходит множество операций, которые лучше обернуть в классический `if` для улучшения читабельности кода

2022-11-02 15:56 UTC, randomroot commented on src/services/actions/amplifierActions/user.js
> +          console.log('ok'),
🟡 **Можно улучшить:**

Логгирование очень полезно на этапе разработки, однако, при сдаче работы следует эти моменты удалить из кода, чтобы в консоли было минимальное количество информационных сообщений и легче было отлавливать ошибки после "выхода в релиз" :)

2022-11-02 15:56 UTC, randomroot commented on src/services/actions/amplifierActions/user.js
> +        err.message === 'jwt expired' ?
🟡 **Можно улучшить:**

Обратите внимание, что текст ошибки может измениться, но код 403 - вечен :)

2022-11-02 15:56 UTC, randomroot commented on src/services/actions/amplifierActions/user.js
> +export const udateUserRequest = (form, reflectErrorRequest) => (dispatch) => {
🟡 **Можно улучшить:**

Допущена орфографическая ошибка в названии функции

2022-11-02 15:56 UTC, randomroot commented on src/components/BurgerConstructor/BurgerConstructor.js
> +      dispatch({
🟡 **Можно улучшить:**

Обнулять стор с заказом имеет смысл в момент закрытия модального окна

2022-11-02 15:56 UTC, randomroot commented on src/components/BurgerIngredientsElement/BurgerIngredientsElement.js
> +  let location = useLocation();
🟡 **Можно улучшить:**

Данное значение следует сделать константой, т.к. её значение не изменяется дальше по коду

2022-11-03 11:41 UTC, ilya-120 commented on src/components/App/App.js
> +            <Route path="/login"
Добрый день, не понятно, что нужно сделать, во всех учебных проектах в практикуме у меня именно такая реализация. При попытке перенести <Route непосредственно внутрь ProtectedRouteOnLogin  получаю ошибку utils.ts:757 Uncaught Error: [Protected Route On Login] is not a <Route> component. All component children of <Routes> must be a <Route> or <React.Fragment>)

2022-11-03 15:55 UTC, randomroot commented on src/components/App/App.js
> +            <Route path="/login"
Здравствуйте, если это реализация проверена временем, то она принимается и замечание снимается 👍

2022-11-03 16:11 UTC, randomroot approved these changes
🟢 **Работа принята:**

Все необходимые правки были внесены, код улучшен согласно рекомендациям, критических замечаний больше не имеется, так держать👍

Отличная работа, **желаю вам хорошего дня и успехов в дальнейшем обучении**! 🐈

2022-11-03 19:56 UTC, merged