Sprint 4/step 1
ilya-120/react-burger pull request #6
Opened 2022-11-18 11:46 UTC by ilya-120

2022-11-18 13:41 UTC, randomroot reviewed
- Использование типа `any` в большинстве случае **нецелесообразно**, т.к. этот подход не позволяет анализатору кода своевременно проверять его на ошибки, которые могут быть выявлены на этапе сборки проекта и усложняет вашу работу с кодом, т.к. значения будут неочевидными (см. https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#any)
- Следует типизировать **все утилитарные** функции, например, функции запросов к серверу в файле `api.ts` (сейчас там возвращается обратно `Promise<any>`, что является плохой практикой, следует определить точный тип возвращаемого значения);
- Следует полностью типизировать всё, что относится к **редаксу**: экшены, редьюсеры и сопутствующие функции (папки `services/actions` и `services/reducers`);
- Не следует импортировать `useDispatch`  и `useSelector` напрямую из `react-redux`, они не типизированы и содержат внутри себя `any`, что по факту отключает возможности **TS** по проверке, правильно ли вы передали название/функцию экшены, тот ли `payload` вы задали. Чтобы исправить данную ситуацию вам необходимо создать отдельные константы, которые типизируют данные хуки (внимательно изучите документацию здесь: https://redux.js.org/usage/usage-with-typescript) и отказаться от использования типа `AnyAction`

2022-11-18 13:41 UTC, randomroot commented on src/components/App/App.tsx
>    const location = useLocation();
🔴 **Нужно исправить:**

Следует типизировать значение стейта в `useLocation`: `useLocation<IState>()` описав тип для `backgroundLocation` (при этом не следует использовать `any`

2022-11-18 13:41 UTC, randomroot commented on src/utils/StellarBurgersApi.ts
> +const headers: any = {
🔴 **Нужно исправить:**

Использование `any` считается плохой практикой, используйте возможности вашей IDE для определение нужного типа, например, у `headers` для `fetch` есть свой тип:

![image](https://user-images.githubusercontent.com/15111821/202712094-a5ac2616-fddc-453f-9f51-02d60363646f.png)

2022-11-18 13:41 UTC, randomroot commented on src/components/App/App.tsx
>  import { useDispatch, useSelector } from "react-redux";
🔴 **Нужно исправить:**

Не следует импортировать `useDispatch`  и `useSelector` напрямую из `react-redux`, они не типизированы и содержат внутри себя `any`, что по факту отключает возможности **TS** по проверке, правильно ли вы передали название/функцию экшены, тот ли `payload` вы задали.

Чтобы исправить данную ситуацию вам необходимо создать отдельные константы, которые типизируют данные хуки (внимательно изучите документацию здесь: https://redux.js.org/usage/usage-with-typescript).

2022-11-18 13:41 UTC, randomroot commented on src/components/App/App.tsx
>  import { useDispatch, useSelector } from "react-redux";
🔴 **Нужно исправить:**

Не следует импортировать `useDispatch`  и `useSelector` напрямую из `react-redux`, они не типизированы и содержат внутри себя `any`, что по факту отключает возможности **TS** по проверке, правильно ли вы передали название/функцию экшены, тот ли `payload` вы задали.

Чтобы исправить данную ситуацию вам необходимо создать отдельные константы, которые типизируют данные хуки (внимательно изучите документацию здесь: https://redux.js.org/usage/usage-with-typescript). Если возникнут сложности с теорией, обратитесь к наставнику, он вам обязательно поможет.

2022-11-18 13:41 UTC, randomroot commented on src/components/App/App.tsx
> +    if (token) dispatch((userRequest as any)());
🔴 **Нужно исправить:**

**Здесь и далее по коду:** следует предварительно типизировать `dispatch` и убрать преобразование к `any`, использование `as` является опеределенным хаком TS и должно использоваться только в крайних случаях, когда других способ исправить ситуацию нет.

2022-11-18 13:41 UTC, randomroot commented on src/components/App/App.tsx
> +    (store: AnyAction) => store.ingredients
🔴 **Нужно исправить:**

Типизацию `store` не следует делать равно `AnyAction`, предварительно типизируйте хук `useSelector`, чтобы получить правильный тип для стора автоматически

2022-11-18 13:41 UTC, randomroot commented on src/components/BurgerConstructor/BurgerConstructor.tsx
> +    (dIndex: any, hIndex: any) => {
🔴 **Нужно исправить:**

Опишите конкретный тип у переменных, согласно их наполнению, не используйте `any`

2022-11-18 13:41 UTC, randomroot commented on src/utils/typeData.ts
> +export type TBurgerConstructorElementProps<T> = {
🔴 **Нужно исправить:**

**Здесь и далее по коду:** Типизацию компонентов, которая используется только в них следует перенести непосредственно в их файлы, выделять в отдельный не следует

2022-11-18 13:41 UTC, randomroot commented on src/components/Modal/Modal.tsx
> +    document.addEventListener("keydown", closeByEscape as any);
🔴 **Нужно исправить:**

Приведение к `any` здесь не требуется, ошибка возникает по причине того, что у вас импортирован `KeyboardEvent` из Реакта, который имеет другие свойства под капотом. Удалите импорт в начале файла, у TS есть свой тип с таким же названием - и ошибка уйдет

2022-11-18 13:41 UTC, randomroot commented on src/components/BurgerIngredients/BurgerIngredients.tsx
> +  const onTabClick = (ref: RefObject<any>) => ref.current.scrollIntoView();
🔴 **Нужно исправить:**

Следует типизировать `RefObject` без использования `any`, обратите внимание, что все рефы, которые используют данную функцию имеют конкретный тип `HTMLUListElement`. При замене возникнет у TS вопрос, т.к. переменная может быть равна `null`, но этот момент успешно закрывается путём использования оператором опциональной последовательности (https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/Optional_chaining)

2022-11-18 13:41 UTC, randomroot commented on src/components/BurgerIngredientsType/BurgerIngredientsType.tsx
> +    const ingredientsList = (array: Array<any>) => {
🔴 **Нужно исправить:**

Ниже в функции `map` описан требуемый тип, следует указать его также и в `Array` вместо `<any>`

2022-11-18 15:08 UTC, ilya-120 commented on src/components/App/App.tsx
>  import { useDispatch, useSelector } from "react-redux";
Добрый день, у нас в теории такого не было, это следующий спринт, насколько я понял (все что касается типизации хранилища и работы с ним)!

2022-11-18 15:33 UTC, randomroot commented on src/components/App/App.tsx
>  import { useDispatch, useSelector } from "react-redux";
@ilya-120 добрый день, прошу прощения, действительно, типизация хранилища в следующем спринте, комментарий снимается!

2022-11-22 08:15 UTC, randomroot requested changes
**Здравствуйте!**

Вы успешно скорректировали **практически все** отмеченные в рамках ревью комментарии и улучшили ваш код, однако для успешного завершения работы следует также **поправить** следующий момент:

- Типизацию функций, связанных с `API` следует сделать более конкретной, типизация данных внутри параметра `data` сейчас равна `any` (например в запросе получения ингредиентов, см. https://disk.yandex.ru/i/GeM7CEZIwk5b2g). Для каждого запроса следует определить свой **собственный** тип ответа (за исключением случаев, где они повторяются один в один) и возвращать именно его. Преобразование результата имеет смысл делать в `checkResponse` (как в целом у вас уже сейчас и реализовано).

- Универсальный тип `IApiData` - это не совсем удачная практика, особенно если количество методов и варианта ответа будут увеличиваться (тогда он станет слишком большим, плюс сложно контролировать какие именно ключи существуют в данный момент), но его можно слегка переделать, если, например, воспользоваться дженериком `interface IApiData<T>`, в котором есть уже поле `success` и тип данных в `data` определяется вами через тип `T`. 

**Желаю вам хорошего дня!** 🐈

2022-11-23 07:35 UTC, randomroot requested changes
**Добрый день!**

Осталась еще пара моментов по корректировке типизации: 
- Вы указали тип возвращаемого значения из функции, но внутри функции всё еще присутствует `any`, следует на этапе преобразования в JSON привести к нужному типу данные (подробнее см. в комментариях);
- Следует поправить возвращаемые типы в `getIngredients` и `getOrderNumber`, т.к. часть из них выставляют неправильный тип ответу;

**Хорошего дня!**

2022-11-23 07:35 UTC, randomroot commented on src/utils/StellarBurgersApi.ts
> +export const getIngredients = async (): Promise<IApiData<TIngredient>> => {
🔴 **Нужно исправить:**

Согласно ответу сервера здесь вы получаете не единичный ингредиент, а массив ингредиентов

2022-11-23 07:35 UTC, randomroot commented on src/utils/StellarBurgersApi.ts
> +  return data.order.number;
1) Сейчас `data` имеет тип `any`, что означает отсутствие типизации.
Чтобы решить эту проблему, следует в функции `checkResponse` добавить преобразование к нужному типу:
```typescript
type TResponse<T> = {
  success: boolean;
} & T;

const checkResponse = <T>(res: Response) => {
  return res.ok ? res.json().then(data => data as TResponse<T>) : Promise.reject(res.status);
};
```

2) Из функции возвращается номер, т.е. `number`, а в типизации указано, что возвращается весь объект заказа `TOrder`

2022-11-23 07:35 UTC, randomroot commented on src/services/actions/amplifierActions/orders.ts
> +        })
🟡 **Можно улучшить:**

Не целесообразно диспатчить отдельно ошибку и текст ошибки, лучше вызывать это в одном действии, т.к. по факту это единое целое)

2022-11-23 07:35 UTC, randomroot commented on src/utils/StellarBurgersApi.ts
> +interface IApiData<T> extends Response {
🟡 **Можно улучшить:**

`IApiData` - это уже преобразованный объект результата, в нём не может быть полей из `Response` поэтому расширение здесь излишне

2022-11-23 11:52 UTC, randomroot requested changes
В рамках текущей итерации были произведены корректировки, но их, к сожалению, недостаточно для правильной типизации файла с API, но не беспокойтесь, всё добьем вместе с вами! 🐈 

Обратите внимание на следующие моменты:

- Как вы верно заметили, в ответах сервера присутствует два формата сейчас: первый связан с данными и включает поля `success` и `data`, а второй - токены. Однако не следует смешивать их в одном типе, разделите их на два разных, и передавайте как аргумент для типа с дженериком (как раз с помощью оператора `&` вы можете дополнить ваш тип нужными параметрами). Подробнее в комментариях к коду

- В коде есть теперь два типа `TResponse` и `IApiData` - они взаимоисключаемые. В примере в рамках предыдущего ревью `TResponse` предлагался как базовый тип, который подходит для любого запроса и может быть расширен, на замену `IApiData` (но название можно оставить прежним).

**Ожидаю ваших правок и обращаю ваше внимание, что данная итерация является дополнительной, поэтому если у вас возникают сложности с реализацией, то отпишите в комментариях, разберём!**

2022-11-23 11:52 UTC, randomroot commented on src/utils/StellarBurgersApi.ts
> +export const getIngredients = async (): Promise<IApiData<[TIngredient]>> => {
🔴 **Нужно исправить:**

`[TIngredient]` - это тип массива с одним единственным элементом, `TIngredient[]` - массив любого количества элементов

2022-11-23 11:52 UTC, randomroot commented on src/utils/StellarBurgersApi.ts
> +  { number: any }
🔴 **Нужно исправить:**

Тип был правильным, не нужно менять на `any`

2022-11-23 11:52 UTC, randomroot commented on src/utils/StellarBurgersApi.ts
> +} & T;
🔴 **Нужно исправить:**

`TResponse` в примере прошлого ревью - это базовый тип, т.к. у любого запроса есть поле `success`, а все остальные необходимые поля добавляются через параметр дженерика `T` присоединением другого типа.

`accessToken` и `refreshToken` есть не в каждом ответе с сервера, а только в тех, что связаны с авторизацией (в ответе заказа их нет). Поэтому для таких ответов следует сделать отдельный тип, например `IApiAuthResponse`, в котором лежат эти два поля, а потом их передавать в метод `checkResponse`: `const data = checkResponse<IApiAuthResponse>(...)` - тогда на выходе вы получите:

 `TResponse<IApiAuthResponse> => { success, accessToken, refreshToken }`

Для примера ингредиентов создаётся тип аналогично:
```ts
type TIngredientResponse = {
  data: TIngredient[]
}
```
и тогда на выходе `checkResponse<TIngredientResponse>(res)` лишних полей не будет содержится и на выходе получаем `TReponse<TIngredientResponse> => { success, data }` - типизация получается корректной и чистой.

`IApiData`  в этом случае получается взаимозаменямой с `TResponse` следует оставить только один базовый тип с названием, который вы считаете более предпочтительным.

**Обратите внимание, что данные вопросы типизиации применяются для всех методов в рамках файла**

Просьба перед повторной сдачей проверить, всё ли из описанного выше было понятно и, если есть вопросы, то не стесняйтесь, уточняйте!

2022-11-23 11:52 UTC, randomroot commented on src/services/actions/amplifierActions/orders.ts
> +          type: ERROR_TEXT_GET_ORDER_NUMBER && ERROR_GET_ORDER_NUMBER,
🟡 **Можно улучшить:**

Это выражение в итоге вызовет только `ERROR_GET_ORDER_NUMBER` (см. https://disk.yandex.ru/i/FiaOFOxQcyoiaQ так работает оператор И);

Идея в предыдущем ревью заключалось в том, чтобы в `payload` `ERROR_GET_ORDER_NUMBER` перенести текст ошибки, а не разбивать отдельно на установку флага ошибки и установку текста ошибки

2022-11-23 15:26 UTC, randomroot approved these changes
🟢 **Работа принята:**

Все необходимые правки были внесены, код улучшен согласно рекомендациям, критических замечаний больше не имеется, так держать👍

**Желаю вам хорошего дня и успехов в дальнейшем обучении**! 🐈

2022-11-24 07:17 UTC, merged